import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--wc-bg)",
        "on-background": "var(--wc-on-bg)",
        surface: "var(--wc-surface)",
        "on-surface": "var(--wc-on-surface)",
        "on-surface-variant": "var(--wc-on-surface-variant)",
        "surface-container": "var(--wc-surface-container)",
        "surface-container-high": "var(--wc-surface-container-high)",
        "surface-container-low": "var(--wc-surface-low)",
        "surface-container-lowest": "var(--wc-surface-lowest)",
        "surface-variant": "var(--wc-surface-variant)",
        "surface-bright": "var(--wc-surface)",
        "surface-dim": "var(--wc-surface-container)",
        primary: "var(--wc-primary)",
        "on-primary": "var(--wc-on-primary)",
        "primary-container": "var(--wc-primary-container)",
        "on-primary-container": "var(--wc-on-primary-container)",
        "primary-fixed": "var(--wc-primary-container)",
        "primary-fixed-dim": "var(--wc-primary-container)",
        "on-primary-fixed": "var(--wc-on-primary)",
        "on-primary-fixed-variant": "var(--wc-on-primary-container)",
        secondary: "var(--wc-secondary)",
        "on-secondary": "var(--wc-on-secondary)",
        "secondary-container": "var(--wc-secondary-container)",
        "on-secondary-container": "var(--wc-on-secondary-container)",
        "secondary-fixed": "var(--wc-secondary-container)",
        "secondary-fixed-dim": "var(--wc-secondary-container)",
        "on-secondary-fixed": "var(--wc-on-secondary)",
        "on-secondary-fixed-variant": "var(--wc-on-secondary-container)",
        error: "var(--wc-error)",
        "on-error": "#ffffff",
        "error-container": "var(--wc-error-container)",
        "on-error-container": "#93000a",
        outline: "var(--wc-outline)",
        "outline-variant": "var(--wc-outline-variant)",
        "inverse-surface": "var(--wc-inverse-surface)",
        "inverse-on-surface": "var(--wc-inverse-on-surface)",
        "inverse-primary": "var(--wc-inverse-primary)",
        "surface-tint": "var(--wc-primary)",
        // Keep tertiary as-is (dark grey)
        tertiary: "#26292b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3c3f41",
        "on-tertiary-container": "#a8aaac",
        "tertiary-fixed": "#e0e3e5",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-fixed-variant": "#444749",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        sm: "8px",
        xs: "4px",
        md: "16px",
        "margin-page": "40px",
        xxl: "80px",
        lg: "24px",
        "container-max": "1440px",
        xl: "48px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["Manrope", "ui-sans-serif", "system-ui"],
        body: ["Manrope", "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        "display-xl": ["57px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "title-lg": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "700", letterSpacing: "0.08em" }],
      },
      boxShadow: {
        card: "0 12px 40px rgba(17, 28, 45, 0.08)",
        "card-hover": "0 24px 60px rgba(17, 28, 45, 0.14)",
        glow: "0 0 40px rgba(0, 33, 110, 0.12)",
        "glow-lg": "0 0 80px rgba(0, 33, 110, 0.18)",
        "inner-light": "inset 0 1px 0 rgba(255,255,255,0.6)",
      },
      animation: {
        "gradient-x": "gradient-x 4s ease infinite",
        "float": "float 6s ease-in-out infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "spin-slow": "spin 20s linear infinite",
        "scale-pulse": "scale-pulse 4s ease-in-out infinite",
        "shimmer": "shimmer 2s infinite",
      },
      keyframes: {
        "gradient-x": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(0, 33, 110, 0.15)" },
          "50%": { boxShadow: "0 0 40px rgba(0, 33, 110, 0.3)" },
        },
        "scale-pulse": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.03)" },
        },
        "shimmer": {
          "100%": { transform: "translateX(100%)" },
        },
      },
      transitionTimingFunction: {
        "premium": "cubic-bezier(0.25, 0.4, 0.25, 1)",
      },
    },
  },
  plugins: [forms],
};

export default config;
