import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b6c4ff",
        "surface-container-high": "#dee8ff",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-low": "#f0f3ff",
        "surface-container-highest": "#d8e3fb",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-secondary-fixed": "#241a00",
        background: "#f9f9ff",
        "primary-container": "#0033a0",
        "surface-bright": "#f9f9ff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#8ea6ff",
        "surface-variant": "#d8e3fb",
        "on-surface-variant": "#444653",
        "tertiary-fixed": "#e0e3e5",
        "inverse-surface": "#263143",
        surface: "#f9f9ff",
        secondary: "#735c00",
        "on-surface": "#111c2d",
        "outline-variant": "#c4c5d5",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary": "#ffffff",
        "on-secondary-container": "#745c00",
        "on-background": "#111c2d",
        "on-tertiary-fixed-variant": "#444749",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dce1ff",
        "on-primary-fixed": "#001550",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffe088",
        "on-tertiary-container": "#a8aaac",
        "on-primary-fixed-variant": "#133ca8",
        "surface-container": "#e7eeff",
        tertiary: "#26292b",
        "on-tertiary-fixed": "#191c1e",
        "secondary-container": "#fed65b",
        "on-error": "#ffffff",
        outline: "#747684",
        primary: "#00216e",
        "inverse-on-surface": "#ecf1ff",
        "surface-tint": "#3456c1",
        "surface-dim": "#cfdaf2",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#e9c349",
        "tertiary-container": "#3c3f41",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        sm: "8px",
        xs: "4px",
        md: "16px",
        "margin-page": "40px",
        xxl: "80px",
        lg: "24px",
        "container-max": "1440px",
        xl: "48px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["Manrope", "ui-sans-serif", "system-ui"],
        body: ["Manrope", "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        "display-xl": ["57px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "title-lg": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "700", letterSpacing: "0.08em" }],
      },
      boxShadow: {
        card: "0 12px 40px rgba(17, 28, 45, 0.08)",
      },
    },
  },
  plugins: [forms],
};

export default config;
